version: "3.2"

services:
  apron-node:
    container_name: apron-node
    image: apron-node:latest
    ports:
      - "9944:9944"
      - "9933:9933"
      - "30333:30333"
    command: bash -c "/apron-node --dev --ws-external --rpc-external --rpc-methods Unsafe"

  apron-frontend:
    container_name: apron-frontend
    image: apron-node:latest
    ports:
      - "3001:3001"
    command: bash -c "cd /apps && serve -p 3001 build"
    depends_on:
      - apron-node

  redis:
    image: redis:latest
    restart: always
    volumes:
      - ./conf/redis.conf:/etc/redis/redis.conf:rw
      - ./data:/data:rw
    command:
      redis-server /etc/redis/redis.conf --appendonly yes

  httpbin:
    image: kennethreitz/httpbin
    restart: always

  gateway:
    image: apron-node:latest
    build: .
    restart: always
    ports:
      - 8080:8080
      - 8082:8082
    volumes:
      - ./logs:/app/logs:rw
    environment:
      - PROXY_PORT=8080
      - ADMIN_ADDR=0.0.0.0:8082
      - REDIS_SERVER=redis:6379
    command: bash -c "/app/gw"
    depends_on:
      - redis
      - httpbin
