version: "3.2"

services:
  apron-node:
    container_name: apron-node
    image: apron-node:latest
    ports:
      - "9944:9944"
      - "9933:9933"
      - "30333:30333"
    command: bash -c "/apron-node --dev --ws-external --rpc-external --rpc-methods Unsafe --base-path /data"
    volumes:
      - ./data:/data

  polkadot-frontend:
    container_name: polkadot-frontend
    image: apron-node:latest
    ports:
      - "3001:3001"
    command: bash -c "cd /apps && serve -p 3001 build"

  apron-gateway:
    container_name: apron-gateway
    image: apron-node:latest
    ports:
      - "8082:8082"
      - "8080:8080"
      - "2145:2145"
    command: bash -c "/gateway"
